#! /usr/bin/env sh

# "Unofficial strict mode" http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

read email

# Exit trap
function finish {
  # All print the e-mail again
  echo $email
}

trap finish EXIT

# Print error
err() {
  echo "error: $@. The e-mail has not been modified." >&2
}

# Initial value for the options
aflag=0
rflag=0

while getopts ":har" opt; do
  case "$opt" in
    a)
      aflag=1
      ;;
    r)
      rflag=1
      ;;
    h|*)
      echo "You should not use this like that."
      exit 0
      ;;
  esac
done

# Sanity test, so $aflag and $rflag should always be different
test $aflag -eq $rflag && {
  err "You must provide exactly one of the -a or -d option"
  exit 1
}

# shift to the argument
shift $((OPTIND-1))
readonly LABEL=$@

test $aflag -eq 1 && {
  echo "Add the '${LABEL}' label"
}

test $rflag -eq 1 && {
  echo "Remove the '${LABEL}' label"
}
